// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea.Persistence.Database;

#nullable disable

namespace Tarea.Persistence.Database.Migrations
{
    [DbContext(typeof(TareaDbContext))]
    [Migration("20240210161208_Actualizacion")]
    partial class Actualizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tarea")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea.Persistence.Database.Models.CategoriaModel", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Categorias", "Tarea");

                    b.HasData(
                        new
                        {
                            IdCategoria = new Guid("674fe0f7-538a-4f79-8520-2daf7fdb4df3"),
                            Descripcion = "Prioritario"
                        },
                        new
                        {
                            IdCategoria = new Guid("8e151dbe-8e80-4a30-88d8-0f4ed406a3d5"),
                            Descripcion = "No Prioritario"
                        });
                });

            modelBuilder.Entity("Tarea.Persistence.Database.Models.TareaModel", b =>
                {
                    b.Property<Guid>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaIdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.HasKey("IdTarea");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("IdTarea");

                    b.ToTable("Tareas", "Tarea");
                });

            modelBuilder.Entity("Tarea.Persistence.Database.Models.TareaModel", b =>
                {
                    b.HasOne("Tarea.Persistence.Database.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
