// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea.Persistence.Database;

#nullable disable

namespace Tarea.Persistence.Database.Migrations
{
    [DbContext(typeof(TareaDbContext))]
    [Migration("20240210164142_Actualizacion2")]
    partial class Actualizacion2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tarea")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea.Persistence.Database.Models.CategoriaModel", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Categorias", "Tarea");

                    b.HasData(
                        new
                        {
                            IdCategoria = new Guid("6f85d7a8-3202-4fef-98ab-0b42bd1c84b9"),
                            Descripcion = "Prioritario"
                        },
                        new
                        {
                            IdCategoria = new Guid("ddd7863c-ed3d-4bb4-b13f-db0021f33655"),
                            Descripcion = "No Prioritario"
                        });
                });

            modelBuilder.Entity("Tarea.Persistence.Database.Models.TareaModel", b =>
                {
                    b.Property<Guid>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Categoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdTarea");

                    b.ToTable("Tareas", "Tarea");
                });
#pragma warning restore 612, 618
        }
    }
}
